trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build VUTProjectApp.csproj --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  displayName: 'dotnet test'
  inputs:
	command: test
	projects: '**\*Tests\*.csproj'
	testRunTitle: "xUnit Test Run"