trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
- script: dotnet build VUTProjectApp.csproj --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'